apiVersion: "kubeflow.org/v1"
kind: "PyTorchJob"
metadata:
  generateName: pyjob-multi-
  namespace: dist-pytorch
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: Never
      template:
        spec:
          containers:
            - name: pytorch
              image: quay.io/selbi/ubi-cuda-py-mnist:v1.17
              resources:
                limits:
                  nvidia.com/gpu: 1
    Worker:
      replicas: 1
      restartPolicy: Never
      template:
        spec:
          containers:
            - name: pytorch
              image: quay.io/selbi/ubi-cuda-py-mnist:v1.17
              resources:
                limits:
                  nvidia.com/gpu: 1
