apiVersion: "kubeflow.org/v1"
kind: "PyTorchJob"
metadata:
  name: pyjob-multi2
  namespace: multinode-demo
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: Never
      template:
        spec:
          containers:
            - name: pytorch
              image: quay.io/selbi/ubi-cuda-py-mnist:v1.17
              resources:
                limits:
                  cpu: 1
                  memory: 4Gi
                  nvidia.com/gpu: 1
    Worker:
      replicas: 1
      restartPolicy: Never
      template:
        spec:
          containers:
            - name: pytorch
              image: quay.io/selbi/ubi-cuda-py-mnist:v1.17
              resources:
                limits:
                  cpu: 1
                  memory: 4Gi
                  nvidia.com/gpu: 1
